types:
  - major:
    description: "Major release"
    keywords:
      - "breaking"
      - "break"
      - "major"
  - minor:
    description: "Minor release"
    keywords: ["feature", "enhancement", "minor"]
  - patch:
    description: "Patch release"
    keywords: ["bugfix", "fix", "patch"]
  - premajor:
    description: "Pre-major release"
    keywords: ["breaking", "break", "major"]
  - preminor:
    description: "Pre-minor release"
    keywords: ["feature", "enhancement", "minor"]
  - prepatch:
    description: "Pre-patch release"
    keywords: ["bugfix", "fix", "patch"]
  - prerelease:
    description: "Prerelease"
    keywords: ["prerelease"]
