# BOF
---
#
AnyChange:
- any 
  - changed-files:
    - any-glob-to-any-file: '*'
# 
git:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - '**/.gitignore'
      - '**/.gitattributes'
#
workflow:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflow/*.yaml'
      - '.github/workflow/*.yml'
#
project:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - 'actions.yml'
#
code:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - 'node/package.json'
      - 'node/**/*'
      - 'actions.yml'
#
test:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - '.mocharc.yml'
      - 'tests/**/*'
#
documentation:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
#
feature:
- any:
  - head-branch: 
    - '^feature'
#
release:
- any:
  - base-branch: 
    - 'main'
...
# EOF
