# BOF 
# DOC: https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
name: 'GitHub Action Release Version'
author: davekpatrick
description: 'GitHub Action to caculate a required release version'
## ------------------------------
inputs:
  apiToken:
   description: 'GitHub API token'
   required: false
  tagPrefix:
    description: 'Release tag prefix character(s) to use'
    required: false
    default: 'v'
  inceptionVersionTag: 
    description: 'The starting point if no prior tags are found'
    required: false
    default: '0.0.0'
  version: 
    description: 'The semver version to use as the current version'
    required: false
  versionInputAsReleaseVersion:
    description: 'Use the current version input as the release version, skipping any version incrementing'
    required: false
    default: 'false'
  configFile:
    description: |
      ## Additonal configuration file
      
      * Overide default fully qualifed location to the configuration file
      * If not found at the specified path, interal specifications will be used
     
      Deafult: 
      ```shell
      ./github/actions/<actionPackageName>/config.yaml
      ```
    required: false
## ------------------------------
outputs:
  versionTag: # id of output
    description: 'The release version tag'
## ------------------------------
branding:
    icon: 'check-circle'
    color: 'green'
## ------------------------------
runs:
  using: 'node22'
  main: 'dist/index.js'
# EOF
