name: default
run-name: Continuous Integration
on:
  push:
    branches-ignore:    
      - main
  pull_request:
jobs:
  # --------------------------------------------
  build:
    name: Artifact build
    strategy:
      matrix:
        operatingSystem: [ubuntu-24.04]
        nodeVersion: [18]
      fail-fast: false
    runs-on: ${{ matrix.operatingSystem }}
    # 
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodeVersion }}
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cd node
        npm install
    - name: Validate
      run: |
        cd node
        npm run validate
    - name: Format
      run: |
        cd node
        npm run format
    - name: Run Unit Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd node
        set | grep GITHUB_
        npm run test
#    - name: Calculate Version
#      id: build-version
#      uses: ./
#      with:
#       tagPrefix: ''
    - name: Build Version
      run: |
        cd node
        npm version 0.2.0
    - name: Compile
      run: |
        cd node
        npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-build-node
        if-no-files-found: error 
        path: |
          node/dist/
          node/package-lock.json
          README.md
          action.yml
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-build-tests
        if-no-files-found: error 
        path: |
          tests/
  # --------------------------------------------
  test:
    name: Artifact Test
    strategy:
      matrix:
        operatingSystem: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-13, macos-14, windows-2022, windows-2019]
        nodeVersion: [16,18]
      fail-fast: false
    runs-on: ${{ matrix.operatingSystem }}
    needs: [build]
    #
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeVersion }}
      - uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ github.event.repository.name }}-build-node
      - uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ github.event.repository.name }}-build-tests
          path: |
            tests/
      - name: Validate setup
        if: ${{ runner.os != 'Windows' }}
        run: |
          node --version
          ls -lR
          set
      - name: Validate setup
        if: ${{ runner.os == 'Windows' }}
        shell: powershell
        run: |
          & node --version
          Set-Location -Path ./
          Get-ChildItem -Recurse
      - name: Build Test
        id: build-test
        uses: ./
        with:
          apiToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Output
        if: ${{ runner.os != 'Windows' }}
        run: |
          echo ${{ steps.build-test.outputs.versionTag }}