on:
  workflow_dispatch:
  push:
  pull_request:
  release:
jobs:
  # --------------------------------------------
  build:
    name: Artifact build
    strategy:
      matrix:
        operatingSystem: [ubuntu-22.04]
        nodeVersion: [18]
      fail-fast: false
    runs-on: ${{ matrix.operatingSystem }}
    # 
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodeVersion }}
    - uses: actions/checkout@v3
    - name: Detach HEAD
      run: |
         git checkout --detach 
         echo "--------------------------------------------"
         git status
         echo "--------------------------------------------"
    - name: Install dependencies
      run: |
        cd node
        npm install
    - name: Install ncc 
      run: |
        cd node
        npm i -g @vercel/ncc@0.36.0
    - name: Compile 
      run: |
        cd node
        ncc build index.js --license licenses.txt
    - name: Execute 
      uses: ./
      with:
        apiToken: ${{ secrets.GITHUB_TOKEN }}
        